# Generated by Django 2.0.7 on 2020-03-14 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_host_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='administrator',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='host',
            name='core_num',
            field=models.SmallIntegerField(choices=[(2, '2 Cores'), (4, '4 Cores'), (6, '6 Cores'), (8, '8 Cores'), (10, '10 Cores'), (12, '12 Cores'), (14, '14 Cores'), (16, '16 Cores'), (18, '18 Cores'), (20, '20 Cores'), (22, '22 Cores'), (24, '24 Cores'), (26, '26 Cores'), (28, '28 Cores')]),
        ),
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=None, to='app.IDC'),
        ),
        migrations.AlterField(
            model_name='host',
            name='service_type',
            field=models.CharField(choices=[('moniter', 'Moniter'), ('lvs', 'LVS'), ('db', 'Database'), ('analysis', 'Analysis'), ('admin', 'Admin'), ('storge', 'Storge'), ('web', 'WEB'), ('email', 'Email'), ('mix', 'Mix')], max_length=32),
        ),
        migrations.AlterField(
            model_name='maintainlog',
            name='host',
            field=models.ForeignKey(on_delete=None, to='app.Host'),
        ),
    ]
